//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chambres_
    {
        public int ID_Chambre_ { get; set; }
        public string TypeChambre { get; set; }
        public Nullable<decimal> PrixNuit { get; set; }
        public string Disponibilite { get; set; }
        public string Description { get; set; }
    }
}
