//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_hotel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbHotel : DbContext
    {
        public DbHotel()
            : base("name=DbHotel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chambres_> Chambres_ { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<Factures> Factures { get; set; }
        public virtual DbSet<Utilisateur_> Utilisateur_ { get; set; }
    }
}
