//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factures
    {
        public int ID_Facture { get; set; }
        public Nullable<int> ID_Reservation { get; set; }
        public Nullable<decimal> MontantTotal { get; set; }
        public Nullable<System.DateTime> DateFacturation { get; set; }
        public string StatutPaiement { get; set; }
    }
}
